### ISSUE TITLE
show locations that have not been visited for the longest time

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#10]
## Value Proposition
As a user, i want to see 5 locations, that haven't been visited for a long time.
## Description
<img width="646" alt="image" src="https://user-images.githubusercontent.com/75478893/223339577-3bd22e9e-a35b-4ba6-8ff8-2b1bb1675fa4.png">

## Acception Criteria
- [ ] On overview page a list of 5 locations that haven't been visited a long time
- [ ] The list is sorted by the oldest visit
- [ ] The list is horizontal scrollable

## Tasks
- [ ] On overview page create a title 'Am längsten nicht besucht'
- [ ] Add a mantine Carousel component below the title
- [ ] Map the 5 visited locations, that haven't been visited for the longest time, into the carousel
