### ISSUE TITLE
show locations that are in other districts than the last 3 visited

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#11]
## Value Proposition
As a user, i want to plan a meetup in a location that is in a different district than the recent 3 meetups, so we have a better dynamic in our meetup locations.

## Description
<img width="649" alt="image" src="https://user-images.githubusercontent.com/75478893/223345217-7676add1-18c5-4c5b-a9f8-f5310be71a10.png">

## Acception Criteria
- [ ] On overview page a list of 5 locations that are in other districts than the last 3 locations
- [ ] The list is horizontal scrollable

## Tasks
- [ ]  On overview page create a title 'Andere Stadtteile'
- [ ] Add a mantine Carousel component below the title
- [ ] Map 5 locations, that are in other districts than the last 3 locations, into the carousel
