### ISSUE TITLE
display a map with all locations

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#12]
## Value Proposition
As a user, i want to see all locations on a map, so that i have an overview of all possible locations.
## Description
<img width="432" alt="image" src="https://user-images.githubusercontent.com/75478893/223439069-3847f115-9220-4ee9-a368-df4b2bc8be7b.png">

## Acception Criteria
- [ ] A page 'Map'
- [ ] A leaflet map that displays all locations

## Tasks
- [ ] Create a page 'Map'
- [ ] Create a map component
- [ ] Create a leaflet map object
- [ ] Render all locations to the map
- [ ] A click on a location opens more information incl. link to the locations details page
