### ISSUE TITLE
highlight relevant locations

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#13]
## Value Proposition
As a user, i want to see the 5 locations, that haven't been visited the longest time and the 5 recently visited, to have an overview in which direction to go next.
## Description
<img width="432" alt="image" src="https://user-images.githubusercontent.com/75478893/223440635-0d742c91-f831-4b93-8551-8fd329472285.png">

## Acception Criteria
- [x] Display 5 highlighted locations, that haven't been visited for a long time on the map
- [x] Display 5 highlighted locations, that recently been visited on the map
## Tasks
- [ ] Create a function, that returns the least and recently visited locations
- [ ] While creating the location markers on the map, check for the above returned locations
- [ ] If location is one of the least visited, highlight it red
- [ ] If location is one of the recently visited, highlight it green
