### ISSUE TITLE
show event list

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#14]
## Value Proposition
As a user, i want to see a list with all events, so that i have an overview of all events in the past.
## Description
<img width="470" alt="image" src="https://user-images.githubusercontent.com/75478893/223449567-22808fa6-2831-4d82-82fe-60ad327b790f.png">

## Acception Criteria
- [x] A new page for events
- [x] A table, that shows the following informations: date, eventName, locationName, capacity, announced, participants, notes
## Tasks
- [x] Create a page 'events'
- [x] Create a table component 'EventTable'
- [x] Create header for date, eventName, locationName, capacity, announced, participants, notes
- [x] Map the events into the table
- [x] Link the locationName to the locations details page
- [x] Link the eventName to the events details page
