### ISSUE TITLE
add event form

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#15]
## Value Proposition
As a user, i want to add a new event, so i can plan an upcoming meetup.
## Description
<img width="217" alt="image" src="https://user-images.githubusercontent.com/75478893/223454150-c0ef4cdf-b02d-4e5f-92e1-2825ed0b159b.png">

## Acception Criteria
- [ ] An 'Create Event' button on Events page
- [ ] Click on Button opens a modal
- [ ] The modal contains a form with following inputs: name, date, location, description, internal notes, announced
- [ ] A form validation
- [ ] Data are added to database
## Tasks
- [ ] Create a button 'Add Event' on Events page
- [ ] OnClick on Button opens a Mantine modal component
- [ ] Inside modal, create a form component
- [ ] Inside the form, create inputs for name, date, location, description, internal notes, announced
- [ ] location must be an autocomplete input, where the location names are mapped in, not editable
- [ ] description must be filled automatically with the locations description, editable
- [ ] Create form validation; all fields are required, except internal notes & announced
- [ ] Create a button 'Create Event'
- [ ] Create a function that adds the data to the database
- [ ] Click on 'Create Event' calls the adding function
