### ISSUE TITLE
edit location

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#22]
## Value Proposition
As a user, I want to edit a location, so i can change the details.
## Description
<img width="300" alt="image" src="https://user-images.githubusercontent.com/75478893/226638680-6e6dda5c-288c-41a8-93dd-68d718201fde.png">

## Acception Criteria
- [ ] A form in a modal
- [ ] The form inputs contain the current details as value
- [ ] Click on 'Save' alters the changes in db
## Tasks
- [ ] Create a function that opens LocationForm with parameter mode={'edit'} in a modal, when edit-button is clicked
- [ ] Set the default values equal to the current db values
- [ ] Create a function, that updates the changed values in db
- [ ] Submit-event of form calls update-function
- [ ] Close Modal and notify user about the change
