### ISSUE TITLE
delete location pictures

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#24]
## Value Proposition
As a user, i want to delete pictures of a location, so i can keep the location's pictures up to date.
## Description
<img width="350" alt="image" src="https://user-images.githubusercontent.com/75478893/227419446-24b2178f-c2cc-4c53-9f40-15429198d226.png">

## Acception Criteria
- [x] A box with all pictures of the location inside
- [x] Click on a picture will ask to delete the picture

## Tasks
- [x] Create a PictureBox component inside the LocationForm in edit mode
- [x] Map all pictures of the location inside the box
- [x] A click on the picture opens a delete modal
- [x] After another click on delete, the cloudinary api will be called to delete the picture
- [x] Delete the picture from the images array
