### ISSUE TITLE
delete location

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#30]
## Value Proposition
As a user, i want to delete a location, so that i can keep my list clean.
## Description
<img width="350" alt="image" src="https://user-images.githubusercontent.com/75478893/229034521-7b085947-05f0-4802-81b6-0f422807d189.png">

## Acception Criteria
- [x] A location delete button
- [x] Placed in Edit Details form
- [x] A Click on 'Location loeschen' opens a modal where you can finally delete the location and all its data
## Tasks
- [x] Create a delete button 'Location loeschen' in LocationForm
- [x] Write a condition, that shows the button only in edit mode
- [x] Highlight the button in red
- [x] Create a modal component 'LocationDeleteModal' and add it to the LocationForm component
- [x] Create a text inside the modal 'Willst du die Location wirklich löschen?'
- [x] Add a final delete button 'Location endgültig löschen'
- [x] Set the modal state to open, when delete button is clicked
- [x] Create a deleteLocation function, that removes the location from State and DB (API)
- [x] The deleteFunction should also delete all associated pictures
- [x] Link the deleteFunction to the final delete button (onClick)
- [x] After deletion, call closeModal to close the modal
