### ISSUE TITLE
external database connection

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#36]
## Value Proposition
As a user, I want to store my data in a cloud database, so that i can access the data from any device.

## Description
< not needed >

## Acception Criteria
- [x] A mongoDB database
- [x] Models for Locations, Tags, Events

## Tasks
- [x] On mongodb.com create a new database "meetin"
- [x] Create a collection for "locations", "events", and "tags"
- [x] Install mongoose
- [x] Create a .env.local file and store the mongodb connection string to MONGODB_URI
- [x] Create a dbConnect.js in lib that handles the mongodb connection
- [x] Create models for Locations, Events and Tags
