### ISSUE TITLE
API functions for locations and tags

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#37]
## Value Proposition
As a user, I want to create locations and save them in a central database, so i have access to it from anywhere.

## Description
< not needed >

## Acception Criteria
- [ ] An API for Locations and Tags with CRUD operations

## Tasks
- [ ] Create CRUD API functions for Locations and Tags
- [ ] Get Locations and Tags from API using serverside props
- [ ] Change location and tag create, edit, delete functions to use api call
