### ISSUE TITLE
create location descriptions using AI

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#40]
## Value Proposition
As a user, I want to create a description for a location automatically, so that i save time while creating new locations.
## Description
// Insert Wire Frame
## Acception Criteria
- [ ] A button for AI text generation in location create / edit formular
- [ ] Click on that button will ask AI to create a 3 sentence description of the given location
## Tasks
- [ ] Visit openai.com and create an API key
- [ ] Store the API key in .env.local as OPENAI_KEY
- [ ] Create and export the function 'getAiLocationDescription' in a file aiLib.tsx in Lib folder
- [ ] The function takes 2 arguments: locationName and cityName
- [ ] Call the openAI API with the key and the command: 'Beschreibe <locationName>, <cityName> in 3 Sätzen.'
- [ ] return the openAI answer
