### ISSUE TITLE
overview page with events and locations

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#45]
## Value Proposition
As a user, I want to see all upcoming events (max. 5), the 5 recent events, and a map with all locations, so that i have an overview over the most important data.
## Description
<img width="350" alt="image" src="https://github.com/sebsch1337/meetin/assets/75478893/2f5771b0-b3f8-48f9-aa6a-2bad4ecd64de">

## Acception Criteria
- [x] A table with all upcoming events (5)
- [x] A table with the 5 recent events
- [x] A map with all locations
- [x] Active locations are blue marked
- [ ] Locations, that haven't been visited the last 6 months, are marked in yellow
- [ ] The 5 longest unvisited locations are marked in red
- [ ] No-go / closed locations are marked in grey
## Tasks
- [ ] On index page, create a table (Datum, Event) component and map the next 5 upcoming events into it
- [ ] Create a table (Datum, Event) next to it with and map the 5 recent events inside
- [ ] Create a leaflet map below the tables
- [ ] Map all locations with their geodata inside, filter out the 5 longest not visited locations and no-go locations, and show them in blue marker
- [ ] Map and filter all locations, where the lastVisited date is higher than 6 months, and display them in yellow on the map
- [ ] Map and filter the 5 locations, with the longest not-visited-date, and display them in red on the map
- [ ] Map and filter all locations with noGo set true and display then in grey.
