### ISSUE TITLE
user authentication

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#71]
## Value Proposition
As a user, I want to protect my data store so that nobody can access my data.
## Acception Criteria
- [ ] Pages are login protected
- [ ] If not logged in, forward to login page
## Tasks
- [ ] Create api/auth/[...nextauth].js with github provider
- [ ] Add oAuth App on github
- [ ] Add homepage url <url>
- [ ] Add authorization callback url <url>/api/auth/callback/github
- [ ] Add GITHUB_ID and GITHUB_SECRET to .env.local and vercel
- [ ] Add SessionProvider to pages/_app.js
- [ ] Add useSession hook to all pages
- [ ] Redirect to index page if session is not logged in
- [ ] Create a login button component that will be shown, when not logged in
- [ ] Create login functionality for login button
- [ ] Change functions and database to match user email adress only
