### ISSUE TITLE
display locations

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#8]
## Value Proposition
As a user, i want to have a list of all locations with their full data, so that i can plan the next meetup.
## Description
<img width="358" alt="image" src="https://user-images.githubusercontent.com/75478893/223332198-ed53c22d-13a4-4b35-a105-0902f7b0b9d5.png">

## Acception Criteria
- [x] A Card with a picture and title of the location
- [x] It shows an average visitors number of the last 3 meetups
- [x] It shows the highest and the lowest visitors number of all meetups
- [x] It shows the number of possible visitors
- [x] It shows the last visit
- [x] It shows the district
- [x] It shows assigned tags
## Tasks
- [x] Create a component LocationCard 
- [x] Create a mantine card component with a Card.Section component for picture
- [x] Create a Title component for the location name
- [x] Create a simple grid component for the additional informations
- [x] Create a function that calculates the average visitors
- [x] Create a function that returns the highest and the lowest number of visitors
- [x] Create a function that returns the latest meetup date in local string
- [x] Display average visitors, highest and lowest number of visitors, last visit, max number of visitors and district inside the simple grid
- [x] Below the grid, display all tags
