### ISSUE TITLE
add new location

### ISSUE THREAD

**Issue by sebsch1337** [sebsch1337/meetin#9]
## Value Proposition
As a user, i want to add  a new location with its basic infos, so i can choose the location for the next event.
## Description
<img width="300" alt="image" src="https://user-images.githubusercontent.com/75478893/223443740-9b37f2c4-25d8-4441-b623-bf26abf9708b.png">

## Acception Criteria
- [x] A button on locations page, to add a new location
- [x] A location form in a modal
- [x] An image upload for the location picture
- [x] Inputs for Name, Description, Information, Address, Max Visitors, District, Tags

## Tasks
- [x] Create a button component 'New Location' with a proper icon
- [x] Create a form component NewLocationForm that opens in a modal, when 'New Location' button clicked
- [x] Create inputs for Name, Description, Information, Address, Max Visitors, District, Tags
- [x] Create form validations, set name, description, max visitors, district as required
- [x] Create a function that adds the location to the db
